### ISSUE TITLE
Telemetry 

### ISSUE THREAD

**Issue by kimanimichael** [nakujaproject/avionicsv2#1]
Using I2C

**Comment by rodneyosodo** [comment]
Done on [this](https://github.com/nakujaproject/N2-onboardTelemetry) repo

**Comment by SammyOina** [comment]
Consider adding additional I2C lines for future components

**Comment by SammyOina** [comment]
@0x6f736f646f there are incomplete nets such as LEDR, MOSI and others

**Comment by rodneyosodo** [comment]
> @0x6f736f646f there are incomplete nets such as LEDR, MOSI and others

For which design?
I was saying the issue shouldn't be on this repo as it doesn't have a telemetry PCB. I agree with you @Mike-Kimani should provide i2c lines for telemetry

**Comment by SammyOina** [comment]
> > @0x6f736f646f there are incomplete nets such as LEDR, MOSI and others
> 
> For which design? I was saying the issue shouldn't be on this repo as it doesn't have a telemetry PCB. I agree with you @Mike-Kimani should provide i2c lines for telemetry

For the telemetry PCB, I can create an issue in that repo instead

**Comment by rodneyosodo** [comment]
Okay

**Comment by kimanimichael** [comment]
I2C lines for telemetry provided.
