### ISSUE TITLE
Review PCB

### ISSUE THREAD

**Issue by kimanimichael** [nakujaproject/avionicsv2#10]
Review avionics PCB files before order [Here](https://github.com/nakujaproject/avionicsv2/tree/main/COMPUTER_PCB)

**Comment by rodneyosodo** [comment]
@Mike-Kimani Provide I2C communication lines for sending data to the telemetry computer

**Comment by rodneyosodo** [comment]
> @Mike-Kimani Provide I2C communication lines for sending data to the telemetry computer

Feedback on this?

**Comment by SammyOina** [comment]
Consider switching buzzer to passive buzzer such as mlt-7525

**Comment by rodneyosodo** [comment]
Also nimeona some strange LED's why those?

**Comment by kimanimichael** [comment]
@0x6f736f646f  I'll provide the I2C lines

**Comment by kimanimichael** [comment]
> Also nimeona some strange LED's why those?

Cool factor.

**Comment by rodneyosodo** [comment]
> > Also nimeona some strange LED's why those?
> 
> Cool factor.

What is a cool factor?
Are they RGB? ama?

**Comment by kimanimichael** [comment]
@SammyOina Comment on this.

**Comment by kimanimichael** [comment]
> > @Mike-Kimani Provide I2C communication lines for sending data to the telemetry computer
> 
> Feedback on this?

Done

**Comment by SammyOina** [comment]
> @SammyOina Comment on this.

of course, RGB is cool. The ws2812b provides a wide range of indicators that can be used to demonstrate different states. They can also be paired up and addressed using a single data line
