### ISSUE TITLE
Add overvoltage protection

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#13]
Add over-voltage protection which shuts down the supply, or clamps the output, when the voltage exceeds a preset level.

**Comment by kimanimichael** [comment]
What exact component do you want us to protect from over-voltage?

**Comment by rodneyosodo** [comment]
All the components.

**Comment by rodneyosodo** [comment]
Specifically on the power input the voltage regulators

**Comment by kimanimichael** [comment]
We'll use specific battery voltage. There is hence no risk of having an overvoltage.

**Comment by rodneyosodo** [comment]
> We'll use specific battery voltage. There is hence no risk of having an overvoltage.

😂That is deciding to ignore the eminent threat.
What if some plugs in a different battery with a different voltage?

**Comment by kimanimichael** [comment]
The Voltage regulator used allows for twice the amount of voltage that is on the schematic. I don't think we will have a problem with overvoltage.

**Comment by rodneyosodo** [comment]
Okay

**Comment by kimanimichael** [comment]
Alright.
