### ISSUE TITLE
Decoupling capacitors

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#16]
Place the decoupling capacitors as close as possible to an integrated circuit (IC) on a PCB layout.
Example c5 and c6 should be as close to the vin and vout respectively on u7

Ref
1. [Here](https://i.stack.imgur.com/ENvPJ.png)

**Comment by kimanimichael** [comment]
I'm redesigning the circuit to move to a rectangular board. I'll do this then.

**Comment by rodneyosodo** [comment]
No problem. Why rectangular though?

**Comment by kimanimichael** [comment]
Allows for more area as the height is adjustable.

**Comment by rodneyosodo** [comment]
> Allows for more area as the height is adjustable.

Do you have an image of how they will be stacked?

**Comment by kimanimichael** [comment]
An avionics bay back to back for Avionics and flight control. The telemetry one could be circular and stacked above the two.

**Comment by rodneyosodo** [comment]
Decoupling capacitors should be placed near the +ve line, c12 and c13 should be near leds

**Comment by kimanimichael** [comment]
They are.
