### ISSUE TITLE
Transistors

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#18]
Why are you using this big transistors?

![Screenshot from 2022-02-01 11-50-13](https://user-images.githubusercontent.com/28790446/151938357-a8cfdd6e-bf58-43a7-9a4e-eec1b22eeb1a.png)

**Comment by kimanimichael** [comment]
I'm supposed to change to smaller ones. Limiting current of 5A.

**Comment by rodneyosodo** [comment]
👍🏿

**Comment by kimanimichael** [comment]
Done.
