### ISSUE TITLE
Connectors

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#25]
Why are we using this connector, can't we use standard connectors?

![Screenshot from 2022-02-01 12-04-50](https://user-images.githubusercontent.com/28790446/151940279-a7e4deb7-3273-4f06-bc54-7dd7e3553571.png)

**Comment by kimanimichael** [comment]
It faces downwards allowing for easier connection of wires to the telemetry PCB. Could you expound on what you mean by a standard connector?

**Comment by rodneyosodo** [comment]
Can't we just just the normal male header pins then we can have them either straight or right angled

**Comment by kimanimichael** [comment]
We can have them angled. Either male or female.

**Comment by rodneyosodo** [comment]
Why is H4 at the middle?

**Comment by rodneyosodo** [comment]
What is H2 for?

**Comment by rodneyosodo** [comment]
Add 12v connectors for the camera

**Comment by rodneyosodo** [comment]
Add 5v and 3.3v connector for telemetry

**Comment by kimanimichael** [comment]
> Why is H4 at the middle?

H4 is just a jumper to complete battery power to the board as explained in the other issue. It's position doesn't really matter.

**Comment by kimanimichael** [comment]
> What is H2 for?

It's a feature that allows for delay when setting up on the rocket.

**Comment by kimanimichael** [comment]
> Add 5v and 3.3v connector for telemetry

+3.3V already added. You need 5V too? What for?

**Comment by rodneyosodo** [comment]
> > Add 5v and 3.3v connector for telemetry
> 
> +3.3V already added. You need 5V too? What for?

For WS2812

**Comment by rodneyosodo** [comment]
> > What is H2 for?
> 
> It's a feature that allows for delay when setting up on the rocket.

Why can't this delay be done in the software as we would have more than 1 minute between arming the avionics and firing ignition

**Comment by rodneyosodo** [comment]
> > Why is H4 at the middle?
> 
> H4 is just a jumper to complete battery power to the board as explained in the other issue. It's position doesn't really matter.

Then why is it at the centre and not at the periphery?

**Comment by kimanimichael** [comment]
Power goes from the screw terminal to the jumper and then to the rest of the circuit. Do you have a technical reason for having it at the periphery? If so, kindly post it here.

**Comment by kimanimichael** [comment]
> > > What is H2 for?
> > 
> > 
> > It's a feature that allows for delay when setting up on the rocket.
> 
> Why can't this delay be done in the software as we would have more than 1 minute between arming the avionics and firing ignition

I still want us to have a testing mode that does not have the delay. This will be done using both software and hardware.

**Comment by rodneyosodo** [comment]
> 

No specific reason. I thought it was a convention

**Comment by rodneyosodo** [comment]
> > > > What is H2 for?
> > > 
> > > 
> > > It's a feature that allows for delay when setting up on the rocket.
> > 
> > 
> > Why can't this delay be done in the software as we would have more than 1 minute between arming the avionics and firing ignition
> 
> I still want us to have a testing mode that does not have the delay. This will be done using both software and hardware.

Okay
