### ISSUE TITLE
VCC connection

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#29]
Is that VCC connected to negative?

![Screenshot from 2022-02-16 18-12-34](https://user-images.githubusercontent.com/28790446/154294677-ef6b3151-8c1f-44b1-bdf6-8840d5ddaa91.png)

**Comment by kimanimichael** [comment]
Deja vu😂

No. This is a jumper that only allows powering the board using the battery when the jumper is connected.

**Comment by rodneyosodo** [comment]
Will a jumper not be a long connection?

**Comment by kimanimichael** [comment]
I don't mean a jumper wire. I mean using the strapping technique. Check [here](https://en.wikipedia.org/wiki/Jumper_(computing))

**Comment by rodneyosodo** [comment]
> Deja vujoy
> 
> No. This is a jumper that only allows powering the board using the battery when the jumper is connected.

You said jumper here

**Comment by kimanimichael** [comment]
> > Deja vujoy
> > No. This is a jumper that only allows powering the board using the battery when the jumper is connected.
> 
> You said jumper here

Yes. The strapping technique uses a jumper. Not a jumper wire but a jumper [here](https://en.wikipedia.org/wiki/Jumper_(computing))

**Comment by rodneyosodo** [comment]
To be done by the documentation
