### ISSUE TITLE
Rename VCC

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#30]
Rename VCC to either +5V or +3.3v for easier review

**Comment by kimanimichael** [comment]
What is 5V? What is 3.3v? Reword the comment to +5V and +3.3v.

**Comment by rodneyosodo** [comment]
> What is 5V? What is 3.3v? Reword the comment to +5V and +3.3v.

Yes

**Comment by rodneyosodo** [comment]
@Mike-Kimani Rename VCC to the exact voltage just for reference purposes as we have many voltage references

**Comment by rodneyosodo** [comment]
To be done by the documentation
