### ISSUE TITLE
Buzzer

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#32]
Check the flight control buzzer circuit

**Comment by kimanimichael** [comment]
> Check the flight control buzzer circuit

It's exactly the same already.

**Comment by rodneyosodo** [comment]
Is it like this?

![Screenshot from 2022-02-04 21-55-13](https://user-images.githubusercontent.com/28790446/154813167-5cb4336b-8924-454a-92c9-f80348d9a2ad.png)

**Comment by kimanimichael** [comment]
Yes.

**Comment by Mike-Kimani** [comment]
#28

**Comment by Mike-Kimani** [comment]
[](https://github.com/nakujaproject/avionicsv2/pull/28)
