### ISSUE TITLE
Change Pressure sensor

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#34]
It seems too expensive at $9 per piece

**Comment by kimanimichael** [comment]
@0x6f736f646f 

For such issues kindly suggest a better alternative from a technical point of view to the one that exists on the board.

**Comment by jamesmacharia861** [comment]
found a cheaper pressure sensor that uses an accelerometer to detect motion states
[1811031937_STMicroelectronics-LIS3DHTR_C15134.pdf](https://github.com/nakujaproject/avionicsv2/files/8259251/1811031937_STMicroelectronics-LIS3DHTR_C15134.pdf)

**Comment by rodneyosodo** [comment]
> found a cheaper pressure sensor that uses an accelerometer to detect motion states [1811031937_STMicroelectronics-LIS3DHTR_C15134.pdf](https://github.com/nakujaproject/avionicsv2/files/8259251/1811031937_STMicroelectronics-LIS3DHTR_C15134.pdf)

@jamesmacharia861 what you have refered to is an accelerometer but this issue we can to change the pressure sensors to obtain altitude data

**Comment by jamesmacharia861** [comment]
DSP310 aka C130156 going at   3.4840 dollars. Its applied in drones and has a favourable voltage consumption of1.2- 3.6V VDD and a low current requirement
[DSP310.pdf](https://github.com/nakujaproject/avionicsv2/files/8321117/DSP310.pdf)
