### ISSUE TITLE
What is rated voltage for pulse led?

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#36]

**Comment by kimanimichael** [comment]
A minimum of 2.8V

**Comment by rodneyosodo** [comment]
Nominal of?

**Comment by kimanimichael** [comment]
Check out the datasheet. [Here](https://datasheet.lcsc.com/lcsc/2006241134_TUOZHAN-TZ-P2-0402GTIA1-0-45T_C688877.pdf)

**Comment by rodneyosodo** [comment]
This is in Chinese

**Comment by kimanimichael** [comment]
Translate the specific part you want or find an English one.
