### ISSUE TITLE
Change esp32

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#37]
Your esp32 isn't recommended for new designs

@WashingtonKK 

## Ref
1 [Espressif](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf)

**Comment by rodneyosodo** [comment]
It is also expensive at $4.8

**Comment by Mike-Kimani** [comment]
@0x6f736f646f 

For such issues kindly suggest a better alternative from a technical point of view to the one that exists on the board.
