### ISSUE TITLE
Capacitor on GPS

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/avionicsv2#40]
The capacitor on the GPS should be in series or parallel?
Because I am assuming you are doing some sort of impedance matching or?

**Comment by kimanimichael** [comment]
From the datasheet.

![Screenshot from 2022-04-15 11-04-15](https://user-images.githubusercontent.com/49106674/163543710-18121c5e-5ef0-4f1e-acdb-ce9e7cf17160.png)

**Comment by rodneyosodo** [comment]
The capacitor around the antenna

**Comment by kimanimichael** [comment]
From the datasheet.
![Screenshot from 2022-04-15 15-54-16](https://user-images.githubusercontent.com/49106674/163573158-540338d7-61f9-46ce-8fad-6406a24ba1cf.png)

**Comment by rodneyosodo** [comment]
Is it a matching circuit or a filtering circuit?

**Comment by kimanimichael** [comment]
Should be matching. Issue also discussed [here.](https://github.com/nakujaproject/avionicsv2/issues/43)

**Comment by rodneyosodo** [comment]
If it is a matching circuit then the cap should be in parallel

**Comment by kimanimichael** [comment]
The parallel arrangement would help tune the frequency but the datasheet says otherwise.

**Comment by kimanimichael** [comment]
@georgebangeboss Thoughts on this?

**Comment by kimanimichael** [comment]
> Should be matching. Issue also discussed [here.](https://github.com/nakujaproject/avionicsv2/issues/43)

It's not a matching circuit. I was wrong on this. It is a series band pass filter.

**Comment by georgebangeboss** [comment]
The capacitor is a DC blocking capacitor
The LNA AT2659 datasheet provides sufficient information about the matching circuits. The datasheet is [here](https://github.com/nakujaproject/avionicsv2/blob/reviews2/GPS/MAX2659.pdf)

Here are photo snippets
![image](https://user-images.githubusercontent.com/57718305/164313542-902767db-195f-4730-9c18-73c5d3a7d94b.png)


![image](https://user-images.githubusercontent.com/57718305/164313639-a806e4cd-a6ed-4a17-9bb0-1f9fac79228a.png)
