### ISSUE TITLE
Review GPS Module

### ISSUE THREAD

**Issue by georgebangeboss** [nakujaproject/avionicsv2#43]

**Comment by georgebangeboss** [comment]
The impedance matching circuits are perfect. What is left is adjusting the  widths of RF tracks to achieve controlled track impedance of 50 Ohms. Is the PCB coplanar or microstrip? What substrate material is being used? FR4? Those are used to calculate the correct track width

The 10 uF Bypass capacitor should be as close as possible to the VCC pin of LNA(AT2659) which seems okay visually

Will the shipped PCB come with the GPS antenna?

**Comment by kimanimichael** [comment]
The PCB is microstrip.

As for the substrate:
![Screenshot from 2022-04-09 11-05-13](https://user-images.githubusercontent.com/49106674/162562884-de11a756-fbc0-408f-bd40-3af5f64dfd04.png)

As per now we'll fabricate the antenna ourselves.

**Comment by georgebangeboss** [comment]
L1_1 and RF nets should be 0.29337mm trace width to achieve 50 Ohm controlled impedance

11.55 mil is equivalent to 0.29337mm

![Screenshot from 2022-04-11 11-09-56](https://user-images.githubusercontent.com/57718305/162820719-d613b040-eeeb-4e2f-8e04-9aeb9f62e279.png)
